
# This file contains all the configurable values for your application, 
# such as image details, replicas, and ingress settings.

# web-app-helm-chart/values.yaml
# Define a custom name for your resources (e.g., web-app)
# Default values for my-webapp
replicaCount: 1

image:
  repository: 281695752858.dkr.ecr.us-east-1.amazonaws.com/jenkinstest # Replace with your image
  tag: latest # Replace with your tag
  pullPolicy: Always
  # platform: linux/arm64  # Explicitly specify platform

service:
  type: ClusterIP
  port: 80


ingress:
  className: "external-nginx"
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix
  tls: []
  annotations: {}
